module.exports = [
  {
    date: "2021-04-01",
    source: "Income",
    amount: 1000,
    item_name: "",
    category: "income",
  },
  {
    date: "2021-04-01",
    source: "Taxes",
    amount: -300,
    item_name: "",
    category: "bills",
  },
  {
    date: "2021-04-01",
    source: "Retirement",
    amount: -200,
    item_name: "",
    category: "savings",
  },
  {
    date: "2021-04-01",
    source: "Savings",
    amount: -100,
    item_name: "",
    category: "savings",
  },
  {
    date: "2021-04-01",
    source: "Credit Card Payment",
    amount: -100,
    item_name: "",
    category: "bills",
  },
  {
    date: "2021-04-05",
    source: "Monthly Birthday Money from Aunt Tilda",
    amount: 20,
    item_name: "",
    category: "income",
  },
  {
    date: "2021-04-05",
    source: "Coffee",
    amount: -4,
    item_name: "",
    category: "restaurants",
  },
  {
    date: "2021-04-05",
    source: "Internet",
    amount: -100,
    item_name: "",
    category: "bills",
  },
  {
    date: "2021-04-03",
    source: "Groceries",
    amount: -76,
    item_name: "",
    category: "grocery",
  },
  {
    date: "2021-04-03",
    source: "Pet Food",
    amount: -7,
    item_name: "",
    category: "grocery",
  },
];
